{% set name = "python-xapian" %}
{% set version = "1.4.20" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://oligarchy.co.uk/xapian/{{ version }}/xapian-bindings-{{ version }}.tar.xz
  sha256: 786cc28d05660b227954413af0e2f66e4ead2a06d3df6dabaea484454b601ef5
  patches:
    - configure_xapian-config_replace_--ltlibs_with_--libs.patch

build:
  number: 0
  skip: true  # [win or python_impl == 'pypy']

requirements:
  build:
    - {{ compiler('cxx') }}
    - make

  host:
    - python
    - pip
    - sphinx
    - sphinx >=4.2.0  # [py==310]
    - xapian-core {{ version }}

  run:
    - python

test:
  imports:
    - xapian

about:
  home: http://xapian.org
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Python bindings for the Xapian Search Engine Library.
  description: |
    Xapian is an Open Source search engine library which allows developers
    to add advanced indexing and search facilities to their own applications.
    It has built-in support for several families of weighting models and also
    supports a rich set of boolean query operators.
  doc_url: https://xapian.org/docs/bindings/
  dev_url: https://xapian.org/bleeding

extra:
  recipe-maintainers:
    - kohr-h
