{% set name = "python-xapian" %}
{% set version = "1.4.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://oligarchy.co.uk/xapian/{{ version }}/xapian-bindings-{{ version }}.tar.xz
  sha256: 9da356c8b20a66ea3d44002e24fee4ed961989d9ba726a13d13e8d56f216718d

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}

  host:
    - python
    - pip
    - sphinx  # TODO: this shouldn't be needed, but there's no way to disable it in configure
    - xapian-core {{ version }}
    - zlib

  run:
    - python

test:
  imports:
    - xapian

about:
  home: http://xapian.org
  license: GPL-2.0+
  license_family: GPL
  license_file: COPYING
  summary: Python bindings for the Xapian Search Engine Library.
  description: |
    Xapian is an Open Source search engine library which allows developers
    to add advanced indexing and search facilities to their own applications.
    It has built-in support for several families of weighting models and also
    supports a rich set of boolean query operators.
  doc_url: https://xapian.org/docs/bindings/
  dev_url: https://xapian.org/bleeding

extra:
  recipe-maintainers:
    - kohr-h
