{% set name = "python-xapian" %}
{% set version = "1.4.16" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://oligarchy.co.uk/xapian/{{ version }}/xapian-bindings-{{ version }}.tar.xz
  sha256: 8791ec6d15cdd2fa065e414033d0b1cd5cf61916fdb47ae5d36c3dfe69be621b
  patches:
    - configure_xapian-config_replace_--ltlibs_with_--libs.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}

  host:
    - python
    - pip
    - sphinx
    - xapian-core {{ version }}

  run:
    - python

test:
  imports:
    - xapian

about:
  home: http://xapian.org
  license: GPL-2.0+
  license_family: GPL
  license_file: COPYING
  summary: Python bindings for the Xapian Search Engine Library.
  description: |
    Xapian is an Open Source search engine library which allows developers
    to add advanced indexing and search facilities to their own applications.
    It has built-in support for several families of weighting models and also
    supports a rich set of boolean query operators.
  doc_url: https://xapian.org/docs/bindings/
  dev_url: https://xapian.org/bleeding

extra:
  recipe-maintainers:
    - kohr-h
