travis:
  secure:
    BINSTAR_TOKEN: T7EaHpmwuBYR9OHEjbIq+zNi13QAzjB9mj+SK1h/i7Jug+9ihfCVqRSrH5hx/FXPY3RibTKyS+fnxqMTVvasrgMVmCaWDZOMtACq2CbvASYxxCY8PGAA7S3cYAcKYogKrAZekRZhQCwSNd2BOrpbQ5ef4FbWWdoSU6oYRtFkZQsGAH/pKKomFne5BCjvvuOp4OAu7ydTDI0qNcpX5qkxKHh1DiGPb+XD47TyQ2OJheTjQVWERHn7yeIoPOSd8nOKWfqacA1lK3tC+SBNPLtPIsbvvPrIyt7v81JhMUtP1MkLaFitVVAcldLro6o9l4xdBz1VcFlaBXPCtYaEe3suWLcYvKzbSp/h0cPvoTjQO9mpyOxckNgcieoOWpHfpczuJbZEWKqnaoDvusjYR2oxvNu36XRuLmtQ+R7TXpvc05w0NEB0ls0LoqO3SHvcYmj9YaKxyJGw/S6fEvdm57jA9MJBpUkWQQgwa5JNMCN1nZgp9L3lPAeckt8oCJMO/C+9tULeIT7yk5MyKfGIGXmXFZGwCgZ9wLwtzXpG4m7QsaXuLd7w2CFcIE+YOLsEGQeZdx/Z630jGEg5TqCVoB2gIn0BbrSy4MLO5+6w26eg8r7frPhHYZ6hDtJP8r51l5p4U6x+dgZl7Yq9fiXSybTZjP+jajdecC1GJf+rLuLqegI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
